# Copyright (c) 2024-2025 HPMicro
# SPDX-License-Identifier: BSD-3-Clause

sdk_inc(.)
sdk_inc(io)
sdk_inc(io/asyncfatfs)

add_subdirectory(blackbox)
add_subdirectory(build)
add_subdirectory(cli)
add_subdirectory(cms)
add_subdirectory(common)
add_subdirectory(config)
add_subdirectory(drivers)
add_subdirectory(fc)
add_subdirectory(flight)
add_subdirectory(io)
add_subdirectory(msp)
add_subdirectory(msc)
add_subdirectory(osd)
add_subdirectory(pg)
add_subdirectory(rx)
add_subdirectory(scheduler)
add_subdirectory(sensors)
add_subdirectory(target)
add_subdirectory(telemetry)

sdk_ses_set_code_placement("drivers/" ".fast")
sdk_ses_set_code_placement("common/" ".fast")
sdk_ses_set_code_placement("fc/" ".fast")
sdk_ses_set_code_placement("flight/" ".fast")
sdk_ses_set_code_placement("pg/" ".fast")
sdk_ses_set_code_placement("scheduler/" ".fast")
sdk_ses_set_code_placement("startup/" ".fast")
sdk_ses_set_code_placement("telemetry/" ".fast")
sdk_ses_set_code_placement("sensors/" ".fast")
sdk_ses_set_code_placement("osd/" ".fast")
sdk_ses_set_code_placement("cms/" ".fast")
sdk_ses_set_code_placement("build/" ".fast")
sdk_ses_set_code_placement("io/" ".fast")
sdk_ses_set_code_placement("config/" ".fast")

sdk_ses_set_optimization_level("drivers/" "Level 2 for speed")
sdk_ses_set_optimization_level("common/" "Level 2 for speed")
sdk_ses_set_optimization_level("fc/" "Level 2 for speed")
sdk_ses_set_optimization_level("flight/" "Level 2 for speed")
sdk_ses_set_optimization_level("pg/" "Level 2 for size")
sdk_ses_set_optimization_level("scheduler/" "Level 2 for speed")
sdk_ses_set_optimization_level("startup/" "Level 2 for speed")
sdk_ses_set_optimization_level("telemetry/" "Level 2 for speed")
sdk_ses_set_optimization_level("sensors/" "Level 2 for speed")
sdk_ses_set_optimization_level("osd/" "Level 2 for speed")
sdk_ses_set_optimization_level("cms/" "Level 2 for size")
sdk_ses_set_optimization_level("build/" "Level 2 for speed")
sdk_ses_set_optimization_level("io/" "Level 2 for size")
sdk_ses_set_optimization_level("config/" "Level 2 for size")