# Copyright 2025 HPMicro
# SPDX-License-Identifier: BSD-3-Clause

sdk_inc(.)

add_subdirectory(accgyro)
add_subdirectory(barometer)
add_subdirectory(compass)
add_subdirectory(hpmicro)
add_subdirectory(rx)

sdk_src(
    inverter.c
    adc.c
    dshot.c
    dshot_command.c
    dshot_dpwm.c
    pwm_output_dshot_shared.c
    buf_writer.c
    bus.c
    bus_i2c_config.c
    bus_i2c_busdev.c
    bus_i2c_utils.c
    bus_i2c_soft.c
    bus_octospi.c
    bus_quadspi.c
    motor.c
    bus_spi.c
    bus_spi_config.c
    bus_spi_pinconfig.c
    buttons.c
    display.c
    display_canvas.c
    dma_common.c
    io.c
    light_led.c
    mco.c
    pinio.c
    pin_pull_up_down.c
    resource.c
    serial.c
    serial_pinconfig.c
    serial_uart.c
    serial_uart_pinconfig.c
    sound_beeper.c
    stack_check.c
    system.c
    timer_common.c
    transponder_ir_arcitimer.c
    transponder_ir_ilap.c
    transponder_ir_erlt.c
    rx/rx_spi.c
    rx/rx_xn297.c
    rx/rx_pwm.c
    serial_softserial.c
    display_ug2864hsweg01.c
    light_ws2811strip.c
    serial_escserial.c
    vtx_common.c
    vtx_table.c
    rx/expresslrs_driver.c
    flash.c
    flash_m25p16.c
    flash_w25q128fv.c
    flash_w25m.c
    sdcard.c
    sdcard_spi.c
    sdcard_sdio_baremetal.c
    sdcard_standard.c
    usb_msc_common.c
    max7456.c
)
